### ISSUE TITLE
FNF lag when computer configuration is very strong

### ISSUE THREAD

**Issue by bonduongchannel** [KadeDev/Funkin#2254]
the video I made is below but when switching characters the FPS drops drastically. Can anyone help me with this. my computer high configuration ram 24gb; Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz 3.40 GHz, windows 10.
https://youtu.be/ChWoluTW4-U

**Comment by EliteMasterEric** [comment]
1. See #1753.
2. The issue here is likely with how the mod is coded. This issue can occur if you load the character as you're switching to them. To prevent this lag, you need to load all the characters into memory at the start of the song, then switch between them. This will of course take a lot of RAM but you have 24GB of it.

For reference:
* https://github.com/CryBitDev/Sonic.exe-source is an example where this issue occurs due to improper coding.
* https://github.com/this-is-bennyk/VS-Bogus/blob/main/source/PlayState.hx#L619 is an example where this is done properly. Instead of storing a single character, you'll need to store all the ones you want to use.

**Comment by bonduongchannel** [comment]
@MasterEric  Thank you very much! I have never seen anyone with such a standard and enthusiastic guide as you! Thank you again :D how can I make friends with you?
