### ISSUE TITLE
Bug Report: everytime i run Lime this happens how can i fix this? 

### ISSUE THREAD

**Issue by Licht9** [KadeDev/Funkin#2287]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below. 
Windows 86_64

## What version of the game are you using? Look in the bottom left corner of the main menu.
I tried with 1.6.2 ,1.7 and 1.5.2
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible. 

I just started the game on debug 

![IMG_20210915_202609](https://user-images.githubusercontent.com/90860857/133687521-bbde03d2-f6d7-411d-80c3-029b07f6fd3d.jpg)

## Please describe your issue. Provide extensive detail and images if possible.

I tried to run Lime test Windows but it crashes so i tried with Lime test Windows -debug and it Said  cannot find asset with ID song/assets/songs/tutorial/Voices.ogg
What do i do now?

**Comment by LevaRiikas** [comment]
It just so happens that for some reason; there is only mp3 files in the tutorial and offsettest folders. Try putting "Inst.ogg" and "Voices.ogg" in the files as well/instead, and you'd find it working. However, keep in mind even after fixing the missing song issue, there is still a bug where it says "Null Object Reference."

Hope this helps! :)

**Comment by EliteMasterEric** [comment]
Those errors in the console have always been there and had no effect. The cause of this particular bug is an update not to Kade, but to one of the dependencies (which explains why the bug occurs on old versions of the game as well).

I've found the root cause of the issue and a workaround fix people can use until an actual fix is put in place.

See #2291.
