### ISSUE TITLE
Enhancement: Notesplashes

### ISSUE THREAD

**Issue by TheRealJake12** [KadeDev/Funkin#2300]
Week 7 Notesplashes just add a lot of QoL into the game. thats it. if theres a reason not to I understand.

**Comment by FoxxWEEWEE** [comment]
dude. u cant add those till week 7 comes out on desktop

**Comment by TheRealJake12** [comment]
> dude. u cant add those till week 7 comes out on desktop

other engines have notesplashes and I was just saying it would be cool.

**Comment by somefnfplayerlol** [comment]
kade won't add note splashes until week 7 is open source

**Comment by glisteningtwilights** [comment]
> kade won't add note splashes until week 7 is open source


That is true but if we find a code that will allow us to add it, then we can add it to our mods manually instead of waiting for KadeDev to add it to the engine.

Other Engines do it so nothing really stops us from doing it.

(very late reply to that but oh well, I very rarely go looking through GitHub users ideas, opinions or bugs so it's better than nothing)
