### ISSUE TITLE
Enhancement: Move BF and GF's voice to vocals track in Tutorial song

### ISSUE THREAD

**Issue by Swapper1** [KadeDev/Funkin#2534]
BF and GF's voices from the Tutorial song should be move to vocals track, so the instrumental theme will use music without any voices.
[tutorial.zip](https://github.com/KadeDev/Kade-Engine/files/7360614/tutorial.zip)

**Comment by dummmmdum** [comment]
then it'll just sound weird

**Comment by EliteMasterEric** [comment]
Just downloaded and listened to your split, GF's voice sounds kind of off in the second half. Not sure how you'd fix it though.

> then it'll just sound weird

Tutorial is the only song that doesn't behave as Swapper1 describes. I believe currently, since the Tutorial song uses only an instrumental track, misses don't mute the voice like they do in the other songs.

**Comment by RagdollClash** [comment]
we have the tutorial stems now, so this should be easy to do

**Comment by Swapper1** [comment]
Already done for now.
